name: sc_cli
description: >
  A CLI for Shortcut

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.0.0
  build_cli_annotations: ^2.0.0
  characters: ^1.2.0
  intl: ^0.17.0
  io: ^1.0.3
  petitparser: ^4.4.0

dev_dependencies:
  build_cli: ^2.0.0
  build_runner: ^2.0.6
  dart_code_metrics: ^4.10.1
  hotreloader: ^3.0.2
  lints: ^1.0.0
  test: ^1.6.0

executables:
  sc: sc_cli
